export const routes = {
  home: "/",
  why: "/why",
  howItWorks: "/how-it-works",
  platform: "/platform",
  lanes: "/lanes",
  lane: (slug: string) => `/lanes/${slug}`,
  features: "/features",
  feature: (slug: string) => `/features/${slug}`,
  cockpit: "/cockpit",
  fundraising: "/fundraising",
  compliance: "/compliance",
  calendar: "/calendar",
  outreach: "/outreach",
  field: "/field",
  counties: "/counties",
  intelligence: "/intelligence",
  governance: "/governance",
  implementation: "/implementation",
  demo: "/demo",
  about: "/about",
  contact: "/contact",
  legal: "/legal",
} as const;
